global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'smart-load-balancer'
    environment: 'development'

# Rule files specifies a list of files from which rules are read
rule_files:
  - "alerts.yml"

# A scrape configuration containing exactly one endpoint to scrape
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Load Balancer Core
  - job_name: 'load-balancer-core'
    static_configs:
      - targets: ['load-balancer-core:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Metrics Agent
  - job_name: 'metrics-agent'
    static_configs:
      - targets: ['metrics-agent:9091']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Kafka Exporter (if we add it later)
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (for host metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor (for container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Remote write configuration (for long-term storage)
remote_write:
  - url: http://thanos-receive:10908/api/v1/receive
    queue_config:
      max_samples_per_send: 1000
      capacity: 10000
      max_shards: 200

# Remote read configuration
remote_read:
  - url: http://thanos-query:10912/api/v1/read
    read_recent: true
