name: Smart Load Balancer CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_VERSION: '8.5'
  JAVA_VERSION: '17'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ env.GRADLE_VERSION }}
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and check project
      run: |
        ./gradlew clean build --no-daemon --warning-mode=all
        ./gradlew check --no-daemon

    - name: Run tests with coverage
      run: |
        ./gradlew test --no-daemon --info
        ./gradlew jacocoTestReport --no-daemon

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/build/reports/tests/
          **/build/reports/jacoco/
        retention-days: 7

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: |
          **/build/reports/
        retention-days: 7

  quality-check:
    name: Quality Checks
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ env.GRADLE_VERSION }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check dependencies
      run: ./gradlew dependencies --configuration compileClasspath --no-daemon

    - name: Check for outdated dependencies
      run: ./gradlew dependencyUpdates --no-daemon

    - name: Verify module structure
      run: |
        ./gradlew projects --no-daemon
        ./gradlew :core:tasks --no-daemon
        ./gradlew :networking:tasks --no-daemon
        ./gradlew :metrics:tasks --no-daemon
        ./gradlew :storage:tasks --no-daemon

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'smart-load-balancer'
        path: '.'
        format: 'HTML'
        args: >
          --failOnCVSS 8
          --skipTestCompile
          --enableRetired

    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          dependency-check-report.html
        retention-days: 30
